make shuffle truly random #31
equeim/unplayer pull request #32
Opened 2018-03-27 00:29 UTC by ronyfadel

seed the PRNG before calling qrand(), or otherwise it will always return the same series of values.

https://github.com/equeim/unplayer/issues/31

2018-03-27 00:31 UTC, ronyfadel commented
Apologies in advance:

I've highlighted the issue and submitted a tentative fix for the issue, but I'm unable to build locally, and I can't find instructions in the project to build the project.

2018-03-31 12:45 UTC, equeim commented
Unfortunately, I will be able to continue work on the project only after 21st April, and I can't publish build intructions too.

2018-03-31 13:43 UTC, ronyfadel commented
No problem, let's try to get the fix in after that date then :)

2018-04-23 15:52 UTC, ronyfadel commented
Hi @equeim, any updates on this? Thank you!

2018-04-24 12:47 UTC, equeim requested changes
Using of std::call_once makes sense only with multithreading, which is not the case. Static boolean condition variable is more than enough in this case.
There no need to create a new member function, you can create it in an anonymous namespace inside .cpp file. Also I think it would be better to leave qrand() calls in place and call qsrand wrapper function in Queue constructor.

2018-04-30 14:11 UTC, ronyfadel commented
Hey @equeim, thank you for the feedback. I've updated the PR, let me know what you think.

2018-04-30 22:35 UTC, merged

2018-05-01 02:04 UTC, benaryorg commented
@equeim Any ETA on the new version in the store/openrepos?

2018-05-01 10:43 UTC, equeim commented
@benaryorg Maybe today, or after a few days. There is a problem with my computer, something with the motherboard. As I don't have money for a new one, I'm using my old PC for now. Developing on it is painful.

2018-05-01 15:16 UTC, Caballlero commented
Very sad to hear that your computer is broke : ( you are a true-professional developer.

2018-05-01 15:29 UTC, equeim commented
Thank you. There are donation links in the README.md file.

2018-05-01 15:29 UTC, Caballlero commented
Yes I got it

2018-05-04 16:21 UTC, ghost commented
Hello equeim
Any plans to fix paypal error?

2018-05-04 18:06 UTC, equeim commented
It may be related to the fact that my PayPal account is personal, not business. Although I was unable to find clear information on requirement of business account for donate buttons. Anyway, why in this case it would show error about email address? I've tried to add aother one to my PayPal account, try this link: https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=arochevdev@gmail.com&item_name=Support%20Unplayer%20development&no_note=1&item_number=1&no_shipping=1&currency_code=EUR. Change EUR to USD if you want donate in dollars.

2018-06-25 01:43 UTC, carlosgonzz commented
Finally the donate are done by an external account: 0JK35074UL6732241 SailfishOS Support only.